config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :doctors, controllers: {
    registrations: 'doctors/registrations',
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords'
  }

  devise_for :patients, controllers: {
    registrations: 'patients/registrations',
    sessions: 'patients/sessions',
    passwords: 'patients/passwords'
  } 

  devise_scope :patient do
    root to: 'patients/sessions#new'
  end

  get 'patients/doctors' => 'patients/doctors#index', as: :patients_doctors
  get 'patients/doctors/:id' => 'patients/doctors#show', as: :patients_doctor
  patch 'patients/appointments/:id/book' => 'patients/appointments#book', as: :book_patients_appointment
  patch 'patients/appointments/:id/cancel' => 'patients/appointments#cancel', as: :cancel_patients_appointment

  get 'patients/appointments' => 'patients/appointments#index', as: :patients_appointments


  get 'patients/appointments_searcher' => 'patients/appointments_searcher#index', as: :patients_appointments_searcher
  
  get 'doctors/appointments' => 'doctors/appointments#index', as: :doctors_appointments
  patch 'doctors/appointments/:id/cancel' => 'doctors/appointments#cancel', as: :cancel_doctors_appointment
  post 'doctors/appointments' => 'doctors/appointments#create'
  get 'doctors/appointments/new' => 'doctors/appointments#new', as: :new_doctors_appointment
  delete 'doctors/appointments/:id' => 'doctors/appointments#destroy', as: :doctors_appointment
end

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-md.mb-4
  %a.navbar-brand(href="/")
    %h2 Higia
  .collapse.navbar-collapse
    %span.navbar-text
      Sistema de turnos web
    %ul.navbar-nav.ml-auto
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle(data-toggle="dropdown")
          %span.oi.oi-calendar(aria-hidden="true")
          Turnos
        .dropdown-menu
          - if current_user.instance_of?(Patient)
            = link_to patients_appointments_path, class: 'dropdown-item' do
              %span.oi.oi-calendar(aria-hidden="true")
              Mis Turnos
            = link_to patients_appointments_searcher_path, class: 'dropdown-item' do
              %span.oi.oi-magnifying-glass(aria-hidden="true")
              Buscador de Turnos
          - else 
            = link_to "Listado de Turnos", doctors_appointments_path, class: 'dropdown-item'
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle(data-toggle="dropdown")
          %span.oi.oi-person(aria-hidden="true")
          = current_user.first_name
        .dropdown-menu
          - if current_user.instance_of?(Patient)
            = link_to edit_patient_registration_path, class: 'dropdown-item' do
              %span.oi.oi-pencil(aria-hidden="true")
              Perfil
          - else
            = link_to edit_doctor_registration_path, class: 'dropdown-item' do
              %span.oi.oi-pencil(aria-hidden="true")
              Perfil
          .dropdown-divider 
          = link_to destroy_user_session_path, method: 'delete', class: 'dropdown-item' do 
            %span.oi.oi-account-logout(aria-hidden="true")
            Salir